services:
    wppconnect-server:
        image: areesmoon/wppconnect-server:v0.0.0
        container_name: wppconnect-server-debug
        restart: always
        env_file: my.env
        ports:
            - 21465:21465
            - 880:80
            - 220:22
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./html:/var/www/html